### ISSUE TITLE
登录post提交的表单哪些是必填项？另外密码加密是如何实现的

### ISSUE THREAD

**Issue by Egrt** [BuddingLab/auth_swust#7]
登录post提交的表单哪些是必填项？另外密码加密是如何实现的

**Comment by bytemain** [comment]
devtools -> network 一栏中即可看到登录需要提交的表单：
```txt
execution: e1s1
_eventId: submit
geolocation: 
username: 51xxxxxxxx
password: xxxx
captcha: xxxx
```

这些表单的值可以解析页面获得：

![image](https://user-images.githubusercontent.com/13938334/103879874-5e1b2d80-5113-11eb-97af-0c181a826a24.png)

注意这里的 execution 是会变的值，每次请求都不一样

---

查看网页源代码
<view-source:http://cas.swust.edu.cn/authserver/login?service=http://myo.swust.edu.cn/mht_shall/a/service/serviceFrontManage/cas> 即可发现加密方法


首先请求 RSA 加密需要的参数，
![image](https://user-images.githubusercontent.com/13938334/103878509-7be79300-5111-11eb-80df-2a80f549be17.png)

然后使用上一步的两个参数生成 RSA 公钥。 
将密码倒序，使用 RSA 加密即可
![image](https://user-images.githubusercontent.com/13938334/103878262-27dcae80-5111-11eb-9f94-c832e1826ae2.png)

**Comment by bytemain** [comment]
教务处用的是这个包里提供的方法：
http://cas.swust.edu.cn/authserver/js/security.js

---

python 实现：
https://github.com/icemage001/10086/blob/master/RSA.py

**Comment by Egrt** [comment]
> devtools -> network 一栏中即可看到登录需要提交的表单：
> 
> ```
> execution: e1s1
> _eventId: submit
> geolocation: 
> username: 51xxxxxxxx
> password: xxxx
> captcha: xxxx
> ```
> 
> 查看网页源代码
> view-source:http://cas.swust.edu.cn/authserver/login?service=http://myo.swust.edu.cn/mht_shall/a/service/serviceFrontManage/cas 即可发现加密方法
> 
> 首先请求 RSA 加密需要的参数，
> ![image](https://user-images.githubusercontent.com/13938334/103878509-7be79300-5111-11eb-80df-2a80f549be17.png)
> 
> 将密码倒序，使用 RSA 加密即可
> ![image](https://user-images.githubusercontent.com/13938334/103878262-27dcae80-5111-11eb-9f94-c832e1826ae2.png)

Nice  太感谢了！
